name: Enigma 2
favicon: null
layout_spectrum: 0.882608960615471
typography_spectrum: 0.41701083560474217
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#057139'
    - '#358b5f'
    - '#23ac6c'
    - '#00552b'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
